"""add_is_template

Revision ID: 605d934325de
Revises: 938dbae052a8
Create Date: 2026-05-24 06:22:48.263389
"""
from alembic import op
import sqlalchemy as sa


revision = '605d934325de'
down_revision = '938dbae052a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_template', sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET is_template = false")
    op.alter_column('documents', 'is_template', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_template')
    # ### end Alembic commands ###

