"""add_saas_subscriptions

Revision ID: 938dbae052a8
Revises: 0002_org_gateway_settings
Create Date: 2026-05-24 05:34:30.078848
"""
from alembic import op
import sqlalchemy as sa


revision = '938dbae052a8'
down_revision = '0002_org_gateway_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subscription_tier', sa.String(length=50), nullable=False, server_default='free'))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='active'))
    op.add_column('organizations', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'subscription_expires_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_tier')
    # ### end Alembic commands ###

