"""add_saas_subscriptions

Revision ID: 938dbae052a8
Revises: 0002_org_gateway_settings
Create Date: 2026-05-24 05:34:30.078848
"""
from alembic import op
import sqlalchemy as sa


revision = '938dbae052a8'
down_revision = '0002_org_gateway_settings'
branch_labels = None
depends_on = None


def upgrade() -> None:
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c["name"] for c in inspector.get_columns("organizations")]

    if "subscription_tier" not in columns:
        op.add_column('organizations', sa.Column('subscription_tier', sa.String(length=50), nullable=False, server_default='free'))
    if "subscription_status" not in columns:
        op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='active'))
    if "subscription_expires_at" not in columns:
        op.add_column('organizations', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'subscription_expires_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_tier')
    # ### end Alembic commands ###

