"""schema hardening: FK ondelete, FK indexes, mfa_challenges, field_attachments

Four things, all of which the audit found (section 9, items 4/5):

1. **ON DELETE.** All 76 foreign keys were ``NO ACTION`` while 14 ORM
   relationships declared ``cascade="all, delete-orphan"``, so cascade existed
   only in Python: any bulk or raw delete failed on a FK violation, and
   deleting an organization had to load every child row of every table into
   the session. Each FK now carries a DB-level ``ondelete`` matching the ORM
   intent, and the relationships carry ``passive_deletes=True``.

   Three deliberate exceptions:
   * ``documents.organization_id`` and ``documents.sender_id`` are ``RESTRICT``
     -- executed documents are legally retained records, so deleting a tenant
     or a sender that still owns documents must raise, not cascade.
   * ``audit_logs.document_id`` keeps the ``SET NULL`` a previous revision gave
     it so audit trails survive a document purge; ``recipient_id`` and
     ``user_id`` now match it.
   * ``subscriptions.plan_id`` is ``RESTRICT``: a plan with live subscribers
     must not be deletable.

2. **FK indexes.** PostgreSQL does not index foreign keys. 15 of the 25
   unindexed FKs are indexed here -- each because it is actually queried, or
   because it is now the child side of a cascade from a row the product really
   does delete. The other 10 are ``*_by_user_id`` provenance columns that
   nothing joins, filters or sorts on, and are deliberately left alone.

3. ``mfa_challenges`` + ``users.mfa_last_used_step`` -- replay state moves out
   of the user-facing ``users.preferences`` JSON blob.

4. ``field_attachments`` -- signer upload metadata moves out of the reserved
   ``"attachment"`` key inside ``fields.options``.


Revision ID: f2b7c81e4a90
Revises: e1a9c3b45d10
Create Date: 2026-08-28 17:46:54.270904
"""
from alembic import op
import sqlalchemy as sa


revision = 'f2b7c81e4a90'
down_revision = 'e1a9c3b45d10'
branch_labels = None
depends_on = None


def _drop_fk(table: str, name: str) -> None:
    """Drop a foreign key that may not exist.

    This revision was autogenerated by diffing the ORM models, which declare a
    ``ForeignKey`` on every such column. The migration chain, however, added
    several of those columns with a bare ``_add_column`` and no constraint --
    ``documents.folder_id``, ``documents.owner_user_id``,
    ``documents.source_template_id``, ``recipients.contact_id`` and
    ``support_tickets.document_id``. A database built by running the
    migrations therefore has 71 of the 76 foreign keys this revision expects,
    and an unguarded ``drop_constraint`` aborts the upgrade on the first one
    missing -- on a *fresh* database as much as an existing one, which would
    also break the ``RUN_MIGRATIONS=1`` entrypoint on boot.

    Dropping conditionally is safe in both directions: the matching
    ``create_foreign_key`` below installs the constraint with the right
    ``ondelete`` whether or not one was there before, so the end state is
    identical for every database.
    """
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "{name}"')
    else:
        try:
            op.drop_constraint(name, table, type_='foreignkey')
        except Exception:  # noqa: BLE001 - best effort on backends without IF EXISTS
            pass


def upgrade() -> None:
    # RecipientStatus.notified: the terminal state for a recipient with no
    # signing obligation (``copy``). Wave 1 had to write ``completed`` on CC
    # recipients to get them past the completion gate, which falsely records
    # that they signed. ALTER TYPE ... ADD VALUE is not transactional on
    # PostgreSQL < 12 and cannot be reversed on any version, so it runs first
    # and IF NOT EXISTS makes the revision re-runnable.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE recipientstatus ADD VALUE IF NOT EXISTS 'notified'")

    op.create_table('mfa_challenges',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_mfa_challenges_expires_at', 'mfa_challenges', ['expires_at'], unique=False)
    op.create_index('ix_mfa_challenges_user_id', 'mfa_challenges', ['user_id'], unique=False)
    op.create_table('field_attachments',
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_attachments_document_id', 'field_attachments', ['document_id'], unique=False)
    op.create_index('ix_field_attachments_field_id', 'field_attachments', ['field_id'], unique=False)
    op.create_index('ix_field_attachments_recipient_id', 'field_attachments', ['recipient_id'], unique=False)
    op.create_index('ix_field_attachments_sha256', 'field_attachments', ['sha256'], unique=False)
    _drop_fk('api_keys', 'api_keys_organization_id_fkey')
    _drop_fk('api_keys', 'api_keys_created_by_user_id_fkey')
    op.create_foreign_key('api_keys_organization_id_fkey', 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('api_keys_created_by_user_id_fkey', 'api_keys', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    _drop_fk('audit_logs', 'audit_logs_document_id_fkey')
    _drop_fk('audit_logs', 'audit_logs_recipient_id_fkey')
    _drop_fk('audit_logs', 'audit_logs_user_id_fkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('audit_logs_recipient_id_fkey', 'audit_logs', 'recipients', ['recipient_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('audit_logs_document_id_fkey', 'audit_logs', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_charges_invoice_id', 'charges', ['invoice_id'], unique=False)
    _drop_fk('charges', 'charges_invoice_id_fkey')
    _drop_fk('charges', 'charges_organization_id_fkey')
    op.create_foreign_key('charges_invoice_id_fkey', 'charges', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('charges_organization_id_fkey', 'charges', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('cloud_targets', 'cloud_targets_organization_id_fkey')
    op.create_foreign_key('cloud_targets_organization_id_fkey', 'cloud_targets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('contact_groups', 'contact_groups_organization_id_fkey')
    op.create_foreign_key('contact_groups_organization_id_fkey', 'contact_groups', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('contacts', 'contacts_organization_id_fkey')
    _drop_fk('contacts', 'contacts_created_by_user_id_fkey')
    op.create_foreign_key('contacts_organization_id_fkey', 'contacts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('contacts_created_by_user_id_fkey', 'contacts', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    _drop_fk('custom_reports', 'custom_reports_created_by_user_id_fkey')
    _drop_fk('custom_reports', 'custom_reports_organization_id_fkey')
    op.create_foreign_key('custom_reports_organization_id_fkey', 'custom_reports', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('custom_reports_created_by_user_id_fkey', 'custom_reports', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_document_favorites_document_id', 'document_favorites', ['document_id'], unique=False)
    _drop_fk('document_favorites', 'document_favorites_user_id_fkey')
    _drop_fk('document_favorites', 'document_favorites_document_id_fkey')
    op.create_foreign_key('document_favorites_user_id_fkey', 'document_favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('document_favorites_document_id_fkey', 'document_favorites', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    _drop_fk('document_versions', 'document_versions_document_id_fkey')
    op.create_foreign_key('document_versions_document_id_fkey', 'document_versions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_documents_org_owner', 'documents', ['organization_id', 'owner_user_id'], unique=False)
    _drop_fk('documents', 'documents_folder_id_fkey')
    _drop_fk('documents', 'documents_source_template_id_fkey')
    _drop_fk('documents', 'documents_sender_id_fkey')
    _drop_fk('documents', 'documents_organization_id_fkey')
    _drop_fk('documents', 'documents_owner_user_id_fkey')
    op.create_foreign_key('documents_source_template_id_fkey', 'documents', 'documents', ['source_template_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('documents_sender_id_fkey', 'documents', 'users', ['sender_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('documents_organization_id_fkey', 'documents', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('documents_owner_user_id_fkey', 'documents', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('documents_folder_id_fkey', 'documents', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_embed_sessions_document_id', 'embed_sessions', ['document_id'], unique=False)
    _drop_fk('embed_sessions', 'embed_sessions_organization_id_fkey')
    _drop_fk('embed_sessions', 'embed_sessions_document_id_fkey')
    op.create_foreign_key('embed_sessions_organization_id_fkey', 'embed_sessions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('embed_sessions_document_id_fkey', 'embed_sessions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_feature_flag_overrides_organization_id', 'feature_flag_overrides', ['organization_id'], unique=False)
    _drop_fk('feature_flag_overrides', 'feature_flag_overrides_organization_id_fkey')
    _drop_fk('feature_flag_overrides', 'feature_flag_overrides_flag_id_fkey')
    op.create_foreign_key('feature_flag_overrides_flag_id_fkey', 'feature_flag_overrides', 'feature_flags', ['flag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('feature_flag_overrides_organization_id_fkey', 'feature_flag_overrides', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('feature_flags', 'feature_flags_updated_by_user_id_fkey')
    op.create_foreign_key('feature_flags_updated_by_user_id_fkey', 'feature_flags', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    _drop_fk('fields', 'fields_document_id_fkey')
    _drop_fk('fields', 'fields_recipient_id_fkey')
    op.create_foreign_key('fields_recipient_id_fkey', 'fields', 'recipients', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fields_document_id_fkey', 'fields', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_folders_parent_id', 'folders', ['parent_id'], unique=False)
    op.create_index('ix_folders_team_id', 'folders', ['team_id'], unique=False)
    _drop_fk('folders', 'folders_organization_id_fkey')
    _drop_fk('folders', 'folders_parent_id_fkey')
    _drop_fk('folders', 'folders_created_by_user_id_fkey')
    _drop_fk('folders', 'folders_team_id_fkey')
    op.create_foreign_key('folders_organization_id_fkey', 'folders', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('folders_parent_id_fkey', 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('folders_created_by_user_id_fkey', 'folders', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('folders_team_id_fkey', 'folders', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_impersonation_sessions_admin_user_id', 'impersonation_sessions', ['admin_user_id'], unique=False)
    _drop_fk('impersonation_sessions', 'impersonation_sessions_admin_user_id_fkey')
    _drop_fk('impersonation_sessions', 'impersonation_sessions_organization_id_fkey')
    op.create_foreign_key('impersonation_sessions_admin_user_id_fkey', 'impersonation_sessions', 'users', ['admin_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('impersonation_sessions_organization_id_fkey', 'impersonation_sessions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('integrations', 'integrations_organization_id_fkey')
    op.create_foreign_key('integrations_organization_id_fkey', 'integrations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('invitations', 'invitations_organization_id_fkey')
    _drop_fk('invitations', 'invitations_invited_by_user_id_fkey')
    op.create_foreign_key('invitations_organization_id_fkey', 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invitations_invited_by_user_id_fkey', 'invitations', 'users', ['invited_by_user_id'], ['id'], ondelete='CASCADE')
    _drop_fk('invoices', 'invoices_organization_id_fkey')
    op.create_foreign_key('invoices_organization_id_fkey', 'invoices', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('notification_preferences', 'notification_preferences_user_id_fkey')
    op.create_foreign_key('notification_preferences_user_id_fkey', 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_notifications_organization_id', 'notifications', ['organization_id'], unique=False)
    _drop_fk('notifications', 'notifications_organization_id_fkey')
    _drop_fk('notifications', 'notifications_user_id_fkey')
    op.create_foreign_key('notifications_organization_id_fkey', 'notifications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _drop_fk('password_reset_tokens', 'password_reset_tokens_user_id_fkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _drop_fk('payment_methods', 'payment_methods_organization_id_fkey')
    op.create_foreign_key('payment_methods_organization_id_fkey', 'payment_methods', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('platform_audit_entries', 'platform_audit_entries_organization_id_fkey')
    _drop_fk('platform_audit_entries', 'platform_audit_entries_actor_user_id_fkey')
    op.create_foreign_key('platform_audit_entries_organization_id_fkey', 'platform_audit_entries', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('platform_audit_entries_actor_user_id_fkey', 'platform_audit_entries', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    _drop_fk('recipients', 'recipients_contact_id_fkey')
    _drop_fk('recipients', 'recipients_document_id_fkey')
    op.create_foreign_key('recipients_document_id_fkey', 'recipients', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('recipients_contact_id_fkey', 'recipients', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    _drop_fk('report_exports', 'report_exports_organization_id_fkey')
    _drop_fk('report_exports', 'report_exports_requested_by_user_id_fkey')
    op.create_foreign_key('report_exports_organization_id_fkey', 'report_exports', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('report_exports_requested_by_user_id_fkey', 'report_exports', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_report_schedules_custom_report_id', 'report_schedules', ['custom_report_id'], unique=False)
    _drop_fk('report_schedules', 'report_schedules_organization_id_fkey')
    _drop_fk('report_schedules', 'report_schedules_custom_report_id_fkey')
    op.create_foreign_key('report_schedules_organization_id_fkey', 'report_schedules', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('report_schedules_custom_report_id_fkey', 'report_schedules', 'custom_reports', ['custom_report_id'], ['id'], ondelete='SET NULL')
    _drop_fk('saved_signatures', 'saved_signatures_user_id_fkey')
    op.create_foreign_key('saved_signatures_user_id_fkey', 'saved_signatures', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    _drop_fk('security_posture', 'security_posture_updated_by_user_id_fkey')
    op.create_foreign_key('security_posture_updated_by_user_id_fkey', 'security_posture', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    _drop_fk('signatures', 'signatures_field_id_fkey')
    _drop_fk('signatures', 'signatures_recipient_id_fkey')
    _drop_fk('signatures', 'signatures_document_id_fkey')
    op.create_foreign_key('signatures_field_id_fkey', 'signatures', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('signatures_recipient_id_fkey', 'signatures', 'recipients', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('signatures_document_id_fkey', 'signatures', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    _drop_fk('signing_tokens', 'signing_tokens_document_id_fkey')
    _drop_fk('signing_tokens', 'signing_tokens_recipient_id_fkey')
    op.create_foreign_key('signing_tokens_document_id_fkey', 'signing_tokens', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('signing_tokens_recipient_id_fkey', 'signing_tokens', 'recipients', ['recipient_id'], ['id'], ondelete='CASCADE')
    _drop_fk('subscriptions', 'subscriptions_organization_id_fkey')
    _drop_fk('subscriptions', 'subscriptions_plan_id_fkey')
    op.create_foreign_key('subscriptions_organization_id_fkey', 'subscriptions', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_support_tickets_assignee_user_id', 'support_tickets', ['assignee_user_id'], unique=False)
    op.create_index('ix_support_tickets_document_id', 'support_tickets', ['document_id'], unique=False)
    _drop_fk('support_tickets', 'support_tickets_assignee_user_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_document_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_organization_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_created_by_user_id_fkey')
    op.create_foreign_key('support_tickets_assignee_user_id_fkey', 'support_tickets', 'users', ['assignee_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('support_tickets_organization_id_fkey', 'support_tickets', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('support_tickets_created_by_user_id_fkey', 'support_tickets', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('support_tickets_document_id_fkey', 'support_tickets', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    _drop_fk('system_logs', 'system_logs_organization_id_fkey')
    op.create_foreign_key('system_logs_organization_id_fkey', 'system_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    _drop_fk('team_members', 'team_members_user_id_fkey')
    _drop_fk('team_members', 'team_members_team_id_fkey')
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    _drop_fk('teams', 'teams_organization_id_fkey')
    op.create_foreign_key('teams_organization_id_fkey', 'teams', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('ticket_messages', 'ticket_messages_ticket_id_fkey')
    _drop_fk('ticket_messages', 'ticket_messages_author_user_id_fkey')
    op.create_foreign_key('ticket_messages_author_user_id_fkey', 'ticket_messages', 'users', ['author_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ticket_messages_ticket_id_fkey', 'ticket_messages', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_usage_events_document_id', 'usage_events', ['document_id'], unique=False)
    _drop_fk('usage_events', 'usage_events_organization_id_fkey')
    _drop_fk('usage_events', 'usage_events_document_id_fkey')
    op.create_foreign_key('usage_events_organization_id_fkey', 'usage_events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('usage_events_document_id_fkey', 'usage_events', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    _drop_fk('user_sessions', 'user_sessions_user_id_fkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('mfa_last_used_step', sa.Integer(), nullable=True))
    _drop_fk('users', 'users_organization_id_fkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    _drop_fk('webhook_deliveries', 'webhook_deliveries_endpoint_id_fkey')
    op.create_foreign_key('webhook_deliveries_endpoint_id_fkey', 'webhook_deliveries', 'webhook_endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    _drop_fk('webhook_endpoints', 'webhook_endpoints_organization_id_fkey')
    op.create_foreign_key('webhook_endpoints_organization_id_fkey', 'webhook_endpoints', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # NOTE: lossy. PostgreSQL cannot remove an enum member, so
    # ``recipientstatus.notified`` survives this downgrade. Any row still
    # holding it must be migrated by hand before downgrading further.
    _drop_fk('webhook_endpoints', 'webhook_endpoints_organization_id_fkey')
    op.create_foreign_key('webhook_endpoints_organization_id_fkey', 'webhook_endpoints', 'organizations', ['organization_id'], ['id'])
    _drop_fk('webhook_deliveries', 'webhook_deliveries_endpoint_id_fkey')
    op.create_foreign_key('webhook_deliveries_endpoint_id_fkey', 'webhook_deliveries', 'webhook_endpoints', ['endpoint_id'], ['id'])
    _drop_fk('users', 'users_organization_id_fkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'mfa_last_used_step')
    _drop_fk('user_sessions', 'user_sessions_user_id_fkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'])
    _drop_fk('usage_events', 'usage_events_document_id_fkey')
    _drop_fk('usage_events', 'usage_events_organization_id_fkey')
    op.create_foreign_key('usage_events_document_id_fkey', 'usage_events', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('usage_events_organization_id_fkey', 'usage_events', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_usage_events_document_id', table_name='usage_events')
    _drop_fk('ticket_messages', 'ticket_messages_author_user_id_fkey')
    _drop_fk('ticket_messages', 'ticket_messages_ticket_id_fkey')
    op.create_foreign_key('ticket_messages_author_user_id_fkey', 'ticket_messages', 'users', ['author_user_id'], ['id'])
    op.create_foreign_key('ticket_messages_ticket_id_fkey', 'ticket_messages', 'support_tickets', ['ticket_id'], ['id'])
    _drop_fk('teams', 'teams_organization_id_fkey')
    op.create_foreign_key('teams_organization_id_fkey', 'teams', 'organizations', ['organization_id'], ['id'])
    _drop_fk('team_members', 'team_members_team_id_fkey')
    _drop_fk('team_members', 'team_members_user_id_fkey')
    op.create_foreign_key('team_members_team_id_fkey', 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('team_members_user_id_fkey', 'team_members', 'users', ['user_id'], ['id'])
    op.drop_index('ix_team_members_user_id', table_name='team_members')
    _drop_fk('system_logs', 'system_logs_organization_id_fkey')
    op.create_foreign_key('system_logs_organization_id_fkey', 'system_logs', 'organizations', ['organization_id'], ['id'])
    _drop_fk('support_tickets', 'support_tickets_created_by_user_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_organization_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_document_id_fkey')
    _drop_fk('support_tickets', 'support_tickets_assignee_user_id_fkey')
    op.create_foreign_key('support_tickets_created_by_user_id_fkey', 'support_tickets', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('support_tickets_organization_id_fkey', 'support_tickets', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('support_tickets_document_id_fkey', 'support_tickets', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('support_tickets_assignee_user_id_fkey', 'support_tickets', 'users', ['assignee_user_id'], ['id'])
    op.drop_index('ix_support_tickets_document_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_assignee_user_id', table_name='support_tickets')
    _drop_fk('subscriptions', 'subscriptions_plan_id_fkey')
    _drop_fk('subscriptions', 'subscriptions_organization_id_fkey')
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key('subscriptions_organization_id_fkey', 'subscriptions', 'organizations', ['organization_id'], ['id'])
    _drop_fk('signing_tokens', 'signing_tokens_recipient_id_fkey')
    _drop_fk('signing_tokens', 'signing_tokens_document_id_fkey')
    op.create_foreign_key('signing_tokens_recipient_id_fkey', 'signing_tokens', 'recipients', ['recipient_id'], ['id'])
    op.create_foreign_key('signing_tokens_document_id_fkey', 'signing_tokens', 'documents', ['document_id'], ['id'])
    _drop_fk('signatures', 'signatures_document_id_fkey')
    _drop_fk('signatures', 'signatures_recipient_id_fkey')
    _drop_fk('signatures', 'signatures_field_id_fkey')
    op.create_foreign_key('signatures_document_id_fkey', 'signatures', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('signatures_recipient_id_fkey', 'signatures', 'recipients', ['recipient_id'], ['id'])
    op.create_foreign_key('signatures_field_id_fkey', 'signatures', 'fields', ['field_id'], ['id'])
    _drop_fk('security_posture', 'security_posture_updated_by_user_id_fkey')
    op.create_foreign_key('security_posture_updated_by_user_id_fkey', 'security_posture', 'users', ['updated_by_user_id'], ['id'])
    _drop_fk('saved_signatures', 'saved_signatures_user_id_fkey')
    op.create_foreign_key('saved_signatures_user_id_fkey', 'saved_signatures', 'users', ['user_id'], ['id'])
    _drop_fk('report_schedules', 'report_schedules_custom_report_id_fkey')
    _drop_fk('report_schedules', 'report_schedules_organization_id_fkey')
    op.create_foreign_key('report_schedules_custom_report_id_fkey', 'report_schedules', 'custom_reports', ['custom_report_id'], ['id'])
    op.create_foreign_key('report_schedules_organization_id_fkey', 'report_schedules', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_report_schedules_custom_report_id', table_name='report_schedules')
    _drop_fk('report_exports', 'report_exports_requested_by_user_id_fkey')
    _drop_fk('report_exports', 'report_exports_organization_id_fkey')
    op.create_foreign_key('report_exports_requested_by_user_id_fkey', 'report_exports', 'users', ['requested_by_user_id'], ['id'])
    op.create_foreign_key('report_exports_organization_id_fkey', 'report_exports', 'organizations', ['organization_id'], ['id'])
    _drop_fk('recipients', 'recipients_document_id_fkey')
    _drop_fk('recipients', 'recipients_contact_id_fkey')
    op.create_foreign_key('recipients_document_id_fkey', 'recipients', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('recipients_contact_id_fkey', 'recipients', 'contacts', ['contact_id'], ['id'])
    _drop_fk('platform_audit_entries', 'platform_audit_entries_actor_user_id_fkey')
    _drop_fk('platform_audit_entries', 'platform_audit_entries_organization_id_fkey')
    op.create_foreign_key('platform_audit_entries_actor_user_id_fkey', 'platform_audit_entries', 'users', ['actor_user_id'], ['id'])
    op.create_foreign_key('platform_audit_entries_organization_id_fkey', 'platform_audit_entries', 'organizations', ['organization_id'], ['id'])
    _drop_fk('payment_methods', 'payment_methods_organization_id_fkey')
    op.create_foreign_key('payment_methods_organization_id_fkey', 'payment_methods', 'organizations', ['organization_id'], ['id'])
    _drop_fk('password_reset_tokens', 'password_reset_tokens_user_id_fkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    _drop_fk('notifications', 'notifications_user_id_fkey')
    _drop_fk('notifications', 'notifications_organization_id_fkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key('notifications_organization_id_fkey', 'notifications', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_notifications_organization_id', table_name='notifications')
    _drop_fk('notification_preferences', 'notification_preferences_user_id_fkey')
    op.create_foreign_key('notification_preferences_user_id_fkey', 'notification_preferences', 'users', ['user_id'], ['id'])
    _drop_fk('invoices', 'invoices_organization_id_fkey')
    op.create_foreign_key('invoices_organization_id_fkey', 'invoices', 'organizations', ['organization_id'], ['id'])
    _drop_fk('invitations', 'invitations_invited_by_user_id_fkey')
    _drop_fk('invitations', 'invitations_organization_id_fkey')
    op.create_foreign_key('invitations_invited_by_user_id_fkey', 'invitations', 'users', ['invited_by_user_id'], ['id'])
    op.create_foreign_key('invitations_organization_id_fkey', 'invitations', 'organizations', ['organization_id'], ['id'])
    _drop_fk('integrations', 'integrations_organization_id_fkey')
    op.create_foreign_key('integrations_organization_id_fkey', 'integrations', 'organizations', ['organization_id'], ['id'])
    _drop_fk('impersonation_sessions', 'impersonation_sessions_organization_id_fkey')
    _drop_fk('impersonation_sessions', 'impersonation_sessions_admin_user_id_fkey')
    op.create_foreign_key('impersonation_sessions_organization_id_fkey', 'impersonation_sessions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('impersonation_sessions_admin_user_id_fkey', 'impersonation_sessions', 'users', ['admin_user_id'], ['id'])
    op.drop_index('ix_impersonation_sessions_admin_user_id', table_name='impersonation_sessions')
    _drop_fk('folders', 'folders_team_id_fkey')
    _drop_fk('folders', 'folders_created_by_user_id_fkey')
    _drop_fk('folders', 'folders_parent_id_fkey')
    _drop_fk('folders', 'folders_organization_id_fkey')
    op.create_foreign_key('folders_team_id_fkey', 'folders', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('folders_created_by_user_id_fkey', 'folders', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('folders_parent_id_fkey', 'folders', 'folders', ['parent_id'], ['id'])
    op.create_foreign_key('folders_organization_id_fkey', 'folders', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_folders_team_id', table_name='folders')
    op.drop_index('ix_folders_parent_id', table_name='folders')
    _drop_fk('fields', 'fields_recipient_id_fkey')
    _drop_fk('fields', 'fields_document_id_fkey')
    op.create_foreign_key('fields_recipient_id_fkey', 'fields', 'recipients', ['recipient_id'], ['id'])
    op.create_foreign_key('fields_document_id_fkey', 'fields', 'documents', ['document_id'], ['id'])
    _drop_fk('feature_flags', 'feature_flags_updated_by_user_id_fkey')
    op.create_foreign_key('feature_flags_updated_by_user_id_fkey', 'feature_flags', 'users', ['updated_by_user_id'], ['id'])
    _drop_fk('feature_flag_overrides', 'feature_flag_overrides_flag_id_fkey')
    _drop_fk('feature_flag_overrides', 'feature_flag_overrides_organization_id_fkey')
    op.create_foreign_key('feature_flag_overrides_flag_id_fkey', 'feature_flag_overrides', 'feature_flags', ['flag_id'], ['id'])
    op.create_foreign_key('feature_flag_overrides_organization_id_fkey', 'feature_flag_overrides', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_feature_flag_overrides_organization_id', table_name='feature_flag_overrides')
    _drop_fk('embed_sessions', 'embed_sessions_document_id_fkey')
    _drop_fk('embed_sessions', 'embed_sessions_organization_id_fkey')
    op.create_foreign_key('embed_sessions_document_id_fkey', 'embed_sessions', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('embed_sessions_organization_id_fkey', 'embed_sessions', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_embed_sessions_document_id', table_name='embed_sessions')
    _drop_fk('documents', 'documents_owner_user_id_fkey')
    _drop_fk('documents', 'documents_organization_id_fkey')
    _drop_fk('documents', 'documents_sender_id_fkey')
    _drop_fk('documents', 'documents_source_template_id_fkey')
    _drop_fk('documents', 'documents_folder_id_fkey')
    op.create_foreign_key('documents_owner_user_id_fkey', 'documents', 'users', ['owner_user_id'], ['id'])
    op.create_foreign_key('documents_organization_id_fkey', 'documents', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('documents_sender_id_fkey', 'documents', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('documents_source_template_id_fkey', 'documents', 'documents', ['source_template_id'], ['id'])
    op.create_foreign_key('documents_folder_id_fkey', 'documents', 'folders', ['folder_id'], ['id'])
    op.drop_index('ix_documents_org_owner', table_name='documents')
    _drop_fk('document_versions', 'document_versions_document_id_fkey')
    op.create_foreign_key('document_versions_document_id_fkey', 'document_versions', 'documents', ['document_id'], ['id'])
    _drop_fk('document_favorites', 'document_favorites_document_id_fkey')
    _drop_fk('document_favorites', 'document_favorites_user_id_fkey')
    op.create_foreign_key('document_favorites_document_id_fkey', 'document_favorites', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('document_favorites_user_id_fkey', 'document_favorites', 'users', ['user_id'], ['id'])
    op.drop_index('ix_document_favorites_document_id', table_name='document_favorites')
    _drop_fk('custom_reports', 'custom_reports_organization_id_fkey')
    _drop_fk('custom_reports', 'custom_reports_created_by_user_id_fkey')
    op.create_foreign_key('custom_reports_organization_id_fkey', 'custom_reports', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('custom_reports_created_by_user_id_fkey', 'custom_reports', 'users', ['created_by_user_id'], ['id'])
    _drop_fk('contacts', 'contacts_created_by_user_id_fkey')
    _drop_fk('contacts', 'contacts_organization_id_fkey')
    op.create_foreign_key('contacts_created_by_user_id_fkey', 'contacts', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('contacts_organization_id_fkey', 'contacts', 'organizations', ['organization_id'], ['id'])
    _drop_fk('contact_groups', 'contact_groups_organization_id_fkey')
    op.create_foreign_key('contact_groups_organization_id_fkey', 'contact_groups', 'organizations', ['organization_id'], ['id'])
    _drop_fk('cloud_targets', 'cloud_targets_organization_id_fkey')
    op.create_foreign_key('cloud_targets_organization_id_fkey', 'cloud_targets', 'organizations', ['organization_id'], ['id'])
    _drop_fk('charges', 'charges_organization_id_fkey')
    _drop_fk('charges', 'charges_invoice_id_fkey')
    op.create_foreign_key('charges_organization_id_fkey', 'charges', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('charges_invoice_id_fkey', 'charges', 'invoices', ['invoice_id'], ['id'])
    op.drop_index('ix_charges_invoice_id', table_name='charges')
    _drop_fk('audit_logs', 'audit_logs_user_id_fkey')
    _drop_fk('audit_logs', 'audit_logs_recipient_id_fkey')
    _drop_fk('audit_logs', 'audit_logs_document_id_fkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('audit_logs_recipient_id_fkey', 'audit_logs', 'recipients', ['recipient_id'], ['id'])
    op.create_foreign_key('audit_logs_document_id_fkey', 'audit_logs', 'documents', ['document_id'], ['id'])
    _drop_fk('api_keys', 'api_keys_created_by_user_id_fkey')
    _drop_fk('api_keys', 'api_keys_organization_id_fkey')
    op.create_foreign_key('api_keys_created_by_user_id_fkey', 'api_keys', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('api_keys_organization_id_fkey', 'api_keys', 'organizations', ['organization_id'], ['id'])
    op.drop_index('ix_field_attachments_sha256', table_name='field_attachments')
    op.drop_index('ix_field_attachments_recipient_id', table_name='field_attachments')
    op.drop_index('ix_field_attachments_field_id', table_name='field_attachments')
    op.drop_index('ix_field_attachments_document_id', table_name='field_attachments')
    op.drop_table('field_attachments')
    op.drop_index('ix_mfa_challenges_user_id', table_name='mfa_challenges')
    op.drop_index('ix_mfa_challenges_expires_at', table_name='mfa_challenges')
    op.drop_table('mfa_challenges')
